apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Sit737
  template:
    metadata:
      labels:
        app: Sit737
    spec:
      containers:
      - name: your-container-name
        image: simarsaggu99/sit323-737-2024-t1-prac7p:1.1.1
        ports:
        - containerPort: 80